version: '3'

networks:
    nginx-php-mysql:

services:

    # nginx
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./api:/var/www/api
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - nginx-php-mysql

    # php
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        volumes:
            - ./api:/var/www/api
        networks:
            - nginx-php-mysql

    # mysql
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        cap_add:
            - SYS_NICE
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_USER: app
            MYSQL_ROOT_PASSWORD: P@ssword!
            MYSQL_PASSWORD: P@ssword!
            MYSQL_DATABASE: app
        networks:
            - nginx-php-mysql